### PR TITLE
Resolve Puppet 4 issues

### PR DESCRIPTION
**Pull request by edestecd**
This seems to make the module work in puppet 4 and in vagrant.
It should also continue to function in 3.x with pluginsync enabled.

MiamiOH would be interested in maintaining this module.

### CODE REVIEW

**Comment by javierbertoli** [comment]
Hi @edestecd. Great to hear that @miamioh would be interested in maintaining this module. Do you want me to transfer it to you personally or to MiamiOH group instead?

**Comment by edestecd** [comment]
No need to transfer the repo, we can use the fork.

However, it would be nice if you:
- Added the following Depreciation notice to the top of the README

```
# [DEPRECATED] tcpwrappers

Development will be continued here:

https://forge.puppet.com/MiamiOH/tcpwrappers

https://github.com/MiamiOH/puppet-tcpwrappers

```
- Release a 999.999.999 version to the Forge with the depreciation notice, so that others can find the updated project.

**Comment by javierbertoli** [comment]
If you prefer, we can do it that way, but it will take a little longer: The README modification will be easy. The forge part will take some more time, as I have not uploaded anything to the forge in a couple of years, and I understand the format has changed... :|

If you want me to transfer the repo to @miamioh, you'll need to remove the repo from that account first. 

Just let  me know :)

**Comment by edestecd** [comment]
@javierbertoli OK, merge this PR and then I will delete the repo from @miamioh, so you can transfer it.  This way I don't lose any commits.

**Comment by javierbertoli** [comment]
Makes sense.  Done.

**Comment by edestecd** [comment]
@javierbertoli, OK deleted.

**Comment by javierbertoli** [comment]
Added you as admin of the repo so you can transfer it to another account where you have admin rights.

**Comment by edestecd** [comment]
@javierbertoli OK seems to have been transferred.

**Pull request merged**
